Repository pyiron/pyiron_workflow, pull requests merged in 2024-03, with the labels that each got.

#214 File copy to
  pyiron_workflow/snippets/files.py
  tests/unit/snippets/test_files.py
Labels: enhancement

#215 File object str
  pyiron_workflow/snippets/files.py
  tests/unit/snippets/test_files.py
Labels: enhancement

#241 Add error message for return item without `channel`
  pyiron_workflow/macro.py
  tests/unit/test_macro.py
Labels: enhancement, format_black

#244 [minor] Semantics
  notebooks/deepdive.ipynb
  pyiron_workflow/channels.py
  pyiron_workflow/composite.py
  pyiron_workflow/draw.py
  pyiron_workflow/macro.py
  pyiron_workflow/meta.py
  pyiron_workflow/node.py
  pyiron_workflow/semantics.py
  pyiron_workflow/workflow.py
  tests/unit/test_composite.py
  tests/unit/test_macro.py
  tests/unit/test_node.py
  tests/unit/test_semantics.py
  tests/unit/test_workflow.py
Labels: format_black

#245 [patch] Refactor interfaces
  pyiron_workflow/channels.py
  pyiron_workflow/composite.py
  pyiron_workflow/create.py
  pyiron_workflow/function.py
  pyiron_workflow/has_interface_mixins.py
  pyiron_workflow/io.py
  pyiron_workflow/macro.py
  pyiron_workflow/semantics.py
  tests/unit/test_create.py
  tests/unit/test_function.py
  tests/unit/test_node.py
Labels: format_black

#246 [minor] Extract responsibility for `run` to its own class
  pyiron_workflow/has_interface_mixins.py
  pyiron_workflow/node.py
  pyiron_workflow/run.py
  tests/integration/test_workflow.py
  tests/unit/test_node.py
  tests/unit/test_run.py
  tests/unit/test_status_management.py
Labels: format_black

#250 [patch] State mixin
  pyiron_workflow/channels.py
  pyiron_workflow/create.py
  pyiron_workflow/has_interface_mixins.py
  pyiron_workflow/run.py
  pyiron_workflow/semantics.py
Labels: format_black

#252 [patch] HasIO mixin
  notebooks/deepdive.ipynb
  pyiron_workflow/channels.py
  pyiron_workflow/function.py
  pyiron_workflow/injection.py
  pyiron_workflow/io.py
  pyiron_workflow/node.py
  tests/integration/test_parallel_speedup.py
  tests/unit/test_channels.py
  tests/unit/test_composite.py
  tests/unit/test_function.py
  tests/unit/test_io.py
Labels: format_black

#255 [patch] Give every node `SingleValue` power
  docs/README.md
  notebooks/deepdive.ipynb
  notebooks/quickstart.ipynb
  pyiron_workflow/function.py
  pyiron_workflow/node.py
  pyiron_workflow/single_output.py
  tests/unit/test_composite.py
  tests/unit/test_function.py
  tests/unit/test_node.py
Labels: format_black

#258 [patch] Has working directory
  pyiron_workflow/has_interface_mixins.py
  pyiron_workflow/node.py
  pyiron_workflow/semantics.py
  pyiron_workflow/working.py
Labels: format_black

#260 [patch] Refactor the storage interface
  pyiron_workflow/composite.py
  pyiron_workflow/node.py
  pyiron_workflow/storage.py
  tests/unit/test_macro.py
  tests/unit/test_node.py
  tests/unit/test_workflow.py
Labels: format_black
