Repository pyiron/pyiron_workflow, pull requests merged in 2024-09, with the labels that each got.

#444 [patch] List-like output for for-loops
  notebooks/quickstart.ipynb
  pyiron_workflow/nodes/for_loop.py
  pyiron_workflow/nodes/static_io.py
  pyiron_workflow/type_hinting.py
  tests/unit/nodes/test_for_loop.py
  tests/unit/test_type_hinting.py
Labels: format_black

#445 [patch] Simplify loop signature
  notebooks/quickstart.ipynb
  pyiron_workflow/nodes/for_loop.py
  tests/integration/test_workflow.py
  tests/unit/nodes/test_for_loop.py
Labels: bug, enhancement

#447 [patch] Extend automatic macro and function node documentation
  pyiron_workflow/mixin/preview.py
  pyiron_workflow/nodes/function.py
  pyiron_workflow/nodes/macro.py
Labels: enhancement, format_black

#452 [patch] Add a developer section to the docs
  docs/README.md
  pyiron_workflow/channels.py
  pyiron_workflow/io.py
  pyiron_workflow/mixin/display_state.py
  pyiron_workflow/mixin/storage.py
Labels: documentation

#454 Correct link of executorlib
  docs/README.md
Labels: patch

#457 [patch] Detatched path
  pyiron_workflow/mixin/semantics.py
  pyiron_workflow/nodes/composite.py
  tests/unit/mixin/test_semantics.py
Labels: enhancement

#462 [patch] change color when failed
  pyiron_workflow/draw.py
Labels: enhancement

#463 Refactor: extract method for what happens before a run
  pyiron_workflow/mixin/run.py
  pyiron_workflow/node.py
Labels: format_black

#464 [patch] Refactor: in-line the status management functionality
  pyiron_workflow/mixin/run.py
  tests/unit/mixin/test_status_management.py
Labels: format_black

#466 [patch] Refactor run
  pyiron_workflow/mixin/run.py
  pyiron_workflow/node.py
Labels: format_black

#467 [patch] `Runnable` flexibility and a new output signal
  pyiron_workflow/io.py
  pyiron_workflow/mixin/run.py
  pyiron_workflow/node.py
  pyiron_workflow/nodes/standard.py
  tests/unit/mixin/test_run.py
  tests/unit/test_node.py
Labels: format_black

#471 [patch] Allow failure
  notebooks/deepdive.ipynb
  pyiron_workflow/mixin/run.py
  pyiron_workflow/node.py
  pyiron_workflow/nodes/composite.py
  pyiron_workflow/workflow.py
  tests/integration/test_workflow.py
  tests/unit/mixin/test_run.py
Labels: enhancement

#473 [patch] uniformly expose `filename` in `Node` storage interface.
  pyiron_workflow/node.py
  tests/unit/test_node.py
Labels: format_black

#474 [patch] Save a recovery file
  notebooks/quickstart.ipynb
  pyiron_workflow/__init__.py
  pyiron_workflow/node.py
  tests/integration/test_workflow.py
  tests/unit/test_node.py
Labels: enhancement, format_black

#480 [patch] Extend @samwaseda's good idea to add colours
  pyiron_workflow/draw.py
Labels: enhancement

#482 [patch] Bump development status to Beta
  docs/README.md
  pyiron_workflow/mixin/run.py
  pyiron_workflow/node.py
  pyproject.toml
Labels: documentation
